const crypto = require("crypto");
const Order = require("../models/Order");

const generateCodPin = async (req, res) => {
  try {
    const { orderId } = req.body;

    if (!orderId) {
      return res.status(400).json({
        success: false,
        message: "Order ID is required.",
      });
    }

    const order = await Order.findById(orderId);

    if (!order) {
      return res.status(404).json({
        success: false,
        message: "Order not found.",
      });
    }

    if (order.paymentMethod !== "cod") {
      return res.status(400).json({
        success: false,
        message: "This order is not a COD order.",
      });
    }

    if (order.paymentStatus === "collected") {
      return res.status(400).json({
        success: false,
        message: "COD payment has already been collected.",
      });
    }

    if (order.codPinStatus === "active") {
      return res.status(400).json({
        success: false,
        message: "A COD PIN is already active for this order.",
      });
    }

    const codPin = crypto
      .randomInt(100000, 1000000)
      .toString();

    order.codPin = codPin;
    order.codPinStatus = "active";
    order.codPinVerifiedAt = null;

    await order.save();

    return res.status(200).json({
      success: true,
      message: "COD PIN generated successfully.",
      codPin,
      order: {
        id: order._id,
        orderNumber: order.orderNumber,
        amount: order.amount,
        paymentStatus: order.paymentStatus,
        codPinStatus: order.codPinStatus,
      },
    });
  } catch (error) {
    console.error("Generate COD PIN error:", error);

    return res.status(500).json({
      success: false,
      message: "Unable to generate COD PIN.",
    });
  }
};

const verifyCodPin = async (req, res) => {
  try {
    const { orderId, pin } = req.body;

    if (!orderId || !pin) {
      return res.status(400).json({
        success: false,
        message: "Order ID and PIN are required.",
      });
    }

    if (!/^\d{6}$/.test(String(pin))) {
      return res.status(400).json({
        success: false,
        message: "PIN must be a 6-digit number.",
      });
    }

    const order = await Order.findById(orderId);

    if (!order) {
      return res.status(404).json({
        success: false,
        message: "Order not found.",
      });
    }

    // Client can only verify their own order.
    if (String(order.client) !== String(req.user.userId)) {
      return res.status(403).json({
        success: false,
        message: "You are not authorized to verify this order.",
      });
    }

    if (order.paymentMethod !== "cod") {
      return res.status(400).json({
        success: false,
        message: "This order is not a COD order.",
      });
    }

    // Payment has already been completed.
    if (order.paymentStatus === "collected") {
      return res.status(400).json({
        success: false,
        message: "COD payment has already been collected.",
      });
    }

    // PIN must have been generated by admin.
    if (order.codPinStatus !== "active") {
      return res.status(400).json({
        success: false,
        message: "This COD PIN is not active.",
      });
    }

    // Verify PIN.
    if (order.codPin !== String(pin)) {
      return res.status(400).json({
        success: false,
        message: "Invalid COD PIN.",
      });
    }

    /*
     * PIN verified successfully.
     *
     * In the current flow, successful PIN verification
     * means the COD payment is completed.
     */
    order.paymentStatus = "collected";
    order.codPinStatus = "used";
    order.codCollectedAt = new Date();

    await order.save();

    return res.status(200).json({
      success: true,
      message: "COD payment completed successfully.",
      order: {
        id: order._id,
        orderNumber: order.orderNumber,
        amount: order.amount,
        paymentMethod: order.paymentMethod,
        paymentStatus: order.paymentStatus,
        codPinStatus: order.codPinStatus,
        codCollectedAt: order.codCollectedAt,
      },
    });
  } catch (error) {
    console.error("Verify COD PIN error:", error);

    return res.status(500).json({
      success: false,
      message: "Unable to verify COD PIN.",
    });
  }
};

module.exports = {
  generateCodPin,
  verifyCodPin,
};